FROM ubuntu:14.04
MAINTAINER docker@ipepe.pl

# install essential locales packages
RUN apt-get update && apt-get install -y locales && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
RUN echo 'LANG="en_US.UTF-8"' > /etc/default/locale
RUN echo 'LANGUAGE="en_US:en"' >> /etc/default/locale
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
